%% Clear and Compile Mex File
clc; clear; close all;
mex  -v CXXFLAGS='$CXXFLAGS -fopenmp' LDFLAGS='$LDFLAGS -fopenmp' ...
        '-I../CppLibraries/eigen-3.4.0' ...
        '../HeatSimulation/HeatSimulation/MEX_Heat_Simulation.cpp'...
        '../HeatSimulation/HeatSimulation/FEM_Simulator.cpp'...
        -outdir HeatSimulators\FEMSimulator
    
    
% "mex COPTIMFLAGS='$COPTIMFLAGS -Ofast -fopenmp -std=c11 -Wall' LDOPTIMFLAGS='$LDOPTIMFLAGS -Ofast -fopenmp -std=c11 -Wall' -outdir +MCmatlab\@model\private .\+MCmatlab\src\finiteElementHeatPropagator.c .\+MCmatlab\src\libut.lib"